// src/components/header/Header.svelte
<script>
	import { page } from '$app/stores';
	let dropdownOpen = false;
	let isConnect = false;
	
</script>

<header>
	<div class="corner">
		<a href="/">
			<img alt="Logo"/>
		</a>
	</div>
	<nav class="flex items-center w-0 justify-between sm:visible sm:w-auto">
		<ul>
			<li class="space-x-5 text-xl inline m-10" class:active={$page.path === '/'}>
				<a class="hidden sm:inline-block text-gray-700 hover:text-indigo-700" sveltekit:prefetch href="/">Home</a>
			</li>
			<li class="space-x-5 text-xl inline m-10" class:active={$page.path === '/exchage'}>
				<a class="hidden sm:inline-block text-gray-700 hover:text-indigo-700" sveltekit:prefetch href="/exchage">Exchage</a>
			</li>
			<li class="space-x-5 text-xl inline m-10" class:active={$page.path === '/assets'}>
				<a class="hidden sm:inline-block text-gray-700 hover:text-indigo-700" sveltekit:prefetch href="/assets">Assets</a>
			</li>
		</ul>
	</nav>
	
	<div class="flex py-4">
		{#if !isConnect}
		<button class="bg-gray-800 hover:bg-gray-900 text-white text-sm px-4 py-2 rounded-full" on:click={() => isConnect = true}>
            CONNECT
		</button>
		{:else}
		<button class="bg-gray-800 hover:bg-gray-900 text-white text-sm px-4 py-2 rounded-full">
			<div class="flex items-center">
				<span class="text-gray-400">0x82….8C7</span>
				<img class="w-4 h-4 mx-2" src="/logo/logo.png" alt="network"/>
				<span class="text-gray-200">ETH</span>
			</div>
		</button>
			
		{/if}
	</div>
	
		
	
	<div class="corner">
		<div on:click={() => dropdownOpen = !dropdownOpen} class="sm:hidden space-y-2 hover:cursor-pointer py-5">
			<span class="w-10 h-1 bg-gray-400 rounded-full block"></span>
			<span class="w-10 h-1 bg-gray-400 rounded-full block"></span>
			<span class="w-10 h-1 bg-gray-400 rounded-full block"></span>
		</div>
	</div>
	{#if dropdownOpen}
		<div class="absolute right-4 mt-14 py-2 w-32 bg-white rounded-md shadow-xl z-20">
			<a sveltekit:prefetch href="/" class="block px-4 py-2 text-sm capitalize text-gray-700 hover:bg-blue-500 hover:text-white">
				Home
			</a>
			<a sveltekit:prefetch href="/exchage" class="block px-4 py-2 text-sm capitalize text-gray-700 hover:bg-blue-500 hover:text-white">
				Exchage
			</a>
			<a sveltekit:prefetch href="/assets" class="block px-4 py-2 text-sm capitalize text-gray-700 hover:bg-blue-500 hover:text-white">
				Assets
			</a>
		</div>
	{/if}
	
</header>

<style>
	header {
		display: flex;
		justify-content: space-between;
	}

	.corner {
		height: 4em;
	}

	.corner a {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 100%;
		height: 100%;
	}

	.corner img {
		width: 3em;
		height: 3em;
		object-fit: contain;
		content:url("/logo/logo.png");
	}

	@media (min-width: 640px) {
		.corner {
			width: 7em;
			height: 4em;
		}

		.corner img {
			width: 6em;
			height: 3em;
			content:url("/logo/logo_pc.png");
		}
	}
</style>

// src/screens/Header/Header.tsx

import { useState } from "react";
import {
    BrowserRouter as Router,
    Switch,
    Route,
    Link
} from "react-router-dom";

import { RootState } from 'reducers'
import { useSelector, useDispatch } from "react-redux"
import { clearWallet, clearBalances } from 'reducers/wallet'
import { onboard } from 'lib/onboard'
import './Header.css'

const Header = () => {
    const dispatch = useDispatch();
    const [dropdownOpen, setDropdownOpen] = useState(false);
    const { isConnect } = useSelector((state: RootState) => state.wallet);

    const onConnect = async () => {
        try {
            await onboard.walletSelect();
            await onboard.walletCheck();
        } catch(e) {
        }
        
    }

    const onDisConnect = () => {
        ////todo:: need bug
        onboard.walletReset();
        localStorage.removeItem('selectedWallet');
        dispatch(clearWallet());
        dispatch(clearBalances());
    }

    return (
        <header>
            <div className="corner">
                <a href="/">
                    <img alt="Logo"/>
                </a>
            </div>
            <nav className="flex items-center w-0 justify-between sm:visible sm:w-auto">
                <ul>
                    <li className="space-x-5 text-xl inline m-10">
                        <Link className="hidden sm:inline-block text-gray-700 hover:text-indigo-700" to="/">Home</Link>
                    </li>
                    <li className="space-x-5 text-xl inline m-10">
                        <Link className="hidden sm:inline-block text-gray-700 hover:text-indigo-700" to="/exchage">Exchage</Link>
                    </li>
                    <li className="space-x-5 text-xl inline m-10">
                        <Link className="hidden sm:inline-block text-gray-700 hover:text-indigo-700" to="/assets">Assets</Link>
                    </li>
                </ul>
            </nav>
            
            <div className="flex py-4">
                {isConnect ? 
                    (
                        <button className="bg-gray-800 hover:bg-gray-900 text-white text-sm px-4 py-2 rounded-full">
                            <div className="flex items-center">
                                <span className="text-gray-400">0x82….8C7</span>
                                <img className="w-4 h-4 mx-2" src="/logo/logo.png" alt="network"/>
                                <span className="text-gray-200">ETH</span>
                            </div>
                        </button>
                    ) :
                    (
                        <button className="bg-gray-800 hover:bg-gray-900 text-white text-sm px-4 py-2 rounded-full" onClick={() => onConnect()}>
                            CONNECT
                        </button>
                    )
                }
            </div>
            
            <div className="corner">
                <div onClick={() => setDropdownOpen(!dropdownOpen)} className="sm:hidden space-y-2 hover:cursor-pointer py-5">
                    <span className="w-10 h-1 bg-gray-400 rounded-full block"></span>
                    <span className="w-10 h-1 bg-gray-400 rounded-full block"></span>
                    <span className="w-10 h-1 bg-gray-400 rounded-full block"></span>
                </div>
            </div>
            {
                dropdownOpen && 
                <div className="absolute right-4 mt-14 py-2 w-32 bg-white rounded-md shadow-xl z-20">
                <Link to="/" className="block px-4 py-2 text-sm capitalize text-gray-700 hover:bg-blue-500 hover:text-white">
                    Home
                </Link>
                <Link to="/exchage" className="block px-4 py-2 text-sm capitalize text-gray-700 hover:bg-blue-500 hover:text-white">
                    Exchage
                </Link>
                <Link to="/assets" className="block px-4 py-2 text-sm capitalize text-gray-700 hover:bg-blue-500 hover:text-white">
                    Assets
                </Link>
            </div>
            }
        </header>
    )
}

export default Header;
